<?php
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/db.php';

$campaigns = [
    [
        'title' => 'Trafik Sigortası Kampanyası',
        'slug' => 'trafik-sigortasi-kampanyasi',
        'description' => 'İlk kez trafik sigortası yaptıracak müşterilerimize özel %25\'e varan indirim fırsatı! 30+ sigorta şirketinden en uygun teklifi alın.',
        'short_description' => 'İlk kez trafik sigortası yaptıracaklara özel %25\'e varan indirim!',
        'discount_text' => '%25 İNDİRİM',
        'icon' => 'fas fa-car',
        'image' => '',
        'bg_color' => '#0066cc',
        'features' => "Anında poliçe çıkarma\nTaksit imkanı\n7/24 yol yardım",
        'link_url' => 'trafik-sigortasi.php',
        'link_text' => 'Teklif Al',
        'start_date' => '2026-01-01',
        'end_date' => '2026-06-30',
        'is_active' => 1,
        'sort_order' => 1,
    ],
    [
        'title' => 'Sağlık Sigortası Kampanyası',
        'slug' => 'saglik-sigortasi-kampanyasi',
        'description' => 'Tamamlayıcı ve özel sağlık sigortası ürünlerinde %20\'ye varan indirimlerle sağlığınızı güvence altına alın.',
        'short_description' => 'Tamamlayıcı ve özel sağlık sigortasında %20 indirim!',
        'discount_text' => '%20 İNDİRİM',
        'icon' => 'fas fa-heartbeat',
        'image' => '',
        'bg_color' => '#28a745',
        'features' => "Geniş hastane ağı\nCheck-up hediyeli\nAile indirimi",
        'link_url' => 'tamamlayici-saglik.php',
        'link_text' => 'Teklif Al',
        'start_date' => '2026-01-01',
        'end_date' => '2026-07-15',
        'is_active' => 1,
        'sort_order' => 2,
    ],
    [
        'title' => 'Kasko + Trafik Paket Kampanyası',
        'slug' => 'kasko-trafik-paket-kampanyasi',
        'description' => 'Kasko ve trafik sigortanızı birlikte yaptırarak %30\'a varan indirim fırsatından yararlanın!',
        'short_description' => 'Kasko + Trafik birlikte %30\'a varan indirim!',
        'discount_text' => '%30 İNDİRİM',
        'icon' => 'fas fa-shield-alt',
        'image' => '',
        'bg_color' => '#6f42c1',
        'features' => "İkisini bir arada\nEkstra %10 paket indirimi\n12 aya varan taksit",
        'link_url' => 'kasko.php',
        'link_text' => 'Teklif Al',
        'start_date' => '2026-01-01',
        'end_date' => '2026-06-30',
        'is_active' => 1,
        'sort_order' => 3,
    ],
    [
        'title' => 'Konut Sigortası Kampanyası',
        'slug' => 'konut-sigortasi-kampanyasi',
        'description' => 'Konut sigortası yaptırana DASK hediye! Evinizi deprem dahil tüm risklere karşı kapsamlı şekilde koruyun.',
        'short_description' => 'Konut sigortası yaptırana DASK hediye!',
        'discount_text' => 'HEDİYELİ',
        'icon' => 'fas fa-home',
        'image' => '',
        'bg_color' => '#e83e8c',
        'features' => "DASK hediyeli\nKombi bakım dahil\nCam kırılması teminatı",
        'link_url' => 'konut-sigortasi.php',
        'link_text' => 'Teklif Al',
        'start_date' => '2026-01-01',
        'end_date' => '2026-08-31',
        'is_active' => 1,
        'sort_order' => 4,
    ],
    [
        'title' => 'Seyahat Sigortası Kampanyası',
        'slug' => 'seyahat-sigortasi-kampanyasi',
        'description' => 'Yurt dışı seyahat sağlık sigortasında %15 indirim! Schengen vizesi için de geçerli poliçe anında elinizde.',
        'short_description' => 'Yurt dışı seyahat sigortasında %15 indirim!',
        'discount_text' => '%15 İNDİRİM',
        'icon' => 'fas fa-plane-departure',
        'image' => '',
        'bg_color' => '#17a2b8',
        'features' => "Schengen onaylı\nCOVID-19 teminatı\nBagaj kaybı dahil",
        'link_url' => 'seyahat-saglik.php',
        'link_text' => 'Teklif Al',
        'start_date' => '2026-01-01',
        'end_date' => '2026-09-30',
        'is_active' => 1,
        'sort_order' => 5,
    ],
    [
        'title' => 'Elektrikli Araç Kasko Kampanyası',
        'slug' => 'elektrikli-arac-kasko-kampanyasi',
        'description' => 'Elektrikli araç kaskonuzda batarya teminatı dahil özel fiyatlarla güvende olun! Şarj istasyonu teminatı da bizden.',
        'short_description' => 'Elektrikli araç kasko: batarya teminatı dahil!',
        'discount_text' => 'YENİ',
        'icon' => 'fas fa-bolt',
        'image' => '',
        'bg_color' => '#fd7e14',
        'features' => "Batarya teminatı dahil\nŞarj istasyonu hasarı\nÖzel servis ağı",
        'link_url' => 'elektrikli-arac-kasko.php',
        'link_text' => 'Teklif Al',
        'start_date' => '2026-01-01',
        'end_date' => '2026-12-31',
        'is_active' => 1,
        'sort_order' => 6,
    ],
];

foreach ($campaigns as $c) {
    $id = saveCampaign($c);
    echo 'Eklendi: ' . $c['title'] . ' (ID: ' . $id . ')' . PHP_EOL;
}
echo 'Toplam ' . count($campaigns) . ' kampanya eklendi.' . PHP_EOL;
